name: Build Chaquopy Bundles

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      python:
        description: 'Host Python (major.minor) to use for builds (e.g. 3.11)'
        required: true
        default: '3.11'
      packages:
        description: 'Comma-separated pip requirements, e.g. "yt-dlp==2025.08.01,pycryptodome==3.19.0"'
        required: true
        default: 'yt-dlp'
      abis:
        description: 'Space-separated ABIs (e.g. "arm64-v8a armeabi-v7a x86_64")'
        required: true
        default: 'arm64-v8a x86_64'
      chaquopy_ref:
        description: 'Chaquopy git ref (branch/tag/commit). Defaults to master'
        required: false
        default: 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout builder repo
        uses: actions/checkout@v4

      - name: Setup Java (Gradle needs JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python (host)
        uses: actions/setup-python@v4
        with:
          python-version: ${{ github.event.inputs.python || '3.11' }}

      - name: Install system build deps (common)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git pkg-config \
            zlib1g-dev libssl-dev libbz2-dev libreadline-dev libsqlite3-dev \
            libffi-dev liblzma-dev libgmp-dev

      - name: Run bundle builder
        env:
          CHAQUOPY_REF: ${{ github.event.inputs.chaquopy_ref || 'master' }}
          OUT_BASE: ${{ github.workspace }}/bundle-output
          EXTRA_INDEX: https://chaquo.com/pypi-13.1
        run: |
          echo "Inputs:"
          echo "  python = ${{ github.event.inputs.python }}"
          echo "  packages = ${{ github.event.inputs.packages }}"
          echo "  abis = ${{ github.event.inputs.abis }}"
          echo "  chaquopy_ref = ${{ github.event.inputs.chaquopy_ref }}"
          PKGS="${{ github.event.inputs.packages }}"
          IFS=',' read -ra REQ_ARR <<< "$PKGS"
          ABIS="${{ github.event.inputs.abis }}"
          read -r -a ABI_ARR <<< "$ABIS"
          ARGS=( --python "${{ github.event.inputs.python }}" )
          for r in "${REQ_ARR[@]}"; do ARGS+=( --package "$r" ); done
          for a in "${ABI_ARR[@]}"; do ARGS+=( --abi "$a" ); done
          echo "Invoking: scripts/build_via_gradle.sh ${ARGS[*]}"
          chmod +x scripts/build_via_gradle.sh
          ./scripts/build_via_gradle.sh "${ARGS[@]}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chaquopy-bundles
          path: bundle-output/